# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170409_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='tag',
            field=models.CharField(max_length=20, unique=True, verbose_name='article tag'),
        ),
    ]
